// Mock database for AP Police SafeStay Intelligence Dashboard
const MOCK_DATA = {
  districts: [
    { id: 'AP-VJA', name: 'NTR Vijayawada', PGs: 184, hotels: 92, checkins: 1420, watchlistMatches: 3, activeSos: 1, complianceScore: 94, occupancy: 82 },
    { id: 'AP-VSKP', name: 'Visakhapatnam City', PGs: 245, hotels: 154, checkins: 2180, watchlistMatches: 5, activeSos: 0, complianceScore: 92, occupancy: 78 },
    { id: 'AP-GNT', name: 'Guntur Urban', PGs: 156, hotels: 68, checkins: 1100, watchlistMatches: 2, activeSos: 2, complianceScore: 88, occupancy: 70 },
    { id: 'AP-TPT', name: 'Tirupati Urban', PGs: 112, hotels: 210, checkins: 3450, watchlistMatches: 1, activeSos: 0, complianceScore: 96, occupancy: 89 },
    { id: 'AP-KRN', name: 'Kurnool District', PGs: 74, hotels: 42, checkins: 650, watchlistMatches: 0, activeSos: 0, complianceScore: 84, occupancy: 61 },
    { id: 'AP-ANTP', name: 'Anantapuramu', PGs: 88, hotels: 38, checkins: 720, watchlistMatches: 4, activeSos: 1, complianceScore: 81, occupancy: 65 },
  ],
  properties: [
    {
      id: 'PROP-001',
      name: 'Venkata Sai Elite Women\'s PG',
      type: 'PG',
      address: 'Gayatri Nagar, Vijayawada',
      district: 'NTR Vijayawada',
      ownerName: 'Ramachandra Rao',
      ownerPhone: '+91 98480 22338',
      totalRooms: 45,
      occupiedRooms: 42,
      complianceScore: 96,
      status: 'verified', // verified, pending, suspended, flagged
      cctvWorking: true,
      fireSafety: true,
      guardDetails: 'Verified (SecureForce Ltd)',
      lastAudit: '2026-05-18'
    },
    {
      id: 'PROP-002',
      name: 'V-Residency Luxury Coliving',
      type: 'PG',
      address: 'Madhurawada, Visakhapatnam',
      district: 'Visakhapatnam City',
      ownerName: 'V. Srinivas',
      ownerPhone: '+91 88970 11422',
      totalRooms: 120,
      occupiedRooms: 98,
      complianceScore: 78,
      status: 'flagged',
      cctvWorking: false,
      fireSafety: true,
      guardDetails: 'Pending Police Verification',
      lastAudit: '2026-06-01'
    },
    {
      id: 'PROP-003',
      name: 'Tirumala Grand Residency',
      type: 'Hotel',
      address: 'Alipiri Road, Tirupati',
      district: 'Tirupati Urban',
      ownerName: 'K. Srinivasa Reddy',
      ownerPhone: '+91 99080 55421',
      totalRooms: 80,
      occupiedRooms: 72,
      complianceScore: 98,
      status: 'verified',
      cctvWorking: true,
      fireSafety: true,
      guardDetails: 'Verified (Tirupati Guard Services)',
      lastAudit: '2026-05-25'
    },
    {
      id: 'PROP-004',
      name: 'Sri Krishna Luxury Stay',
      type: 'Guesthouse',
      address: 'Koretipadu, Guntur',
      district: 'Guntur Urban',
      ownerName: 'Y. Koteswara Rao',
      ownerPhone: '+91 91234 56789',
      totalRooms: 30,
      occupiedRooms: 20,
      complianceScore: 42,
      status: 'pending',
      cctvWorking: false,
      fireSafety: false,
      guardDetails: 'None Provided',
      lastAudit: 'Never Audited'
    },
    {
      id: 'PROP-005',
      name: 'Executive PG for Men',
      type: 'PG',
      address: 'Benz Circle, Vijayawada',
      district: 'NTR Vijayawada',
      ownerName: 'B. Venkat Rao',
      ownerPhone: '+91 94405 12345',
      totalRooms: 50,
      occupiedRooms: 45,
      complianceScore: 90,
      status: 'verified',
      cctvWorking: true,
      fireSafety: true,
      guardDetails: 'Verified (AP Guards)',
      lastAudit: '2026-04-10'
    }
  ],
  liveCheckins: [
    {
      id: 'CHK-1021',
      guestName: 'Anudeep Kurra',
      age: 26,
      phone: '+91 90592 11283',
      idType: 'Aadhar Card',
      idNumber: 'XXXX XXXX 8832',
      idImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&q=80',
      nationality: 'Indian',
      checkinTime: '2026-06-05T18:45:00Z',
      propertyName: 'Venkata Sai Elite Women\'s PG',
      roomNumber: '104',
      watchlistMatch: false,
      watchlistReason: '',
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80',
      status: 'Cleared'
    },
    {
      id: 'CHK-1022',
      guestName: 'Michael Corleone',
      age: 34,
      phone: '+1 (415) 882-9382',
      idType: 'Passport',
      idNumber: 'Z8892182',
      idImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80',
      nationality: 'United States',
      checkinTime: '2026-06-05T19:02:00Z',
      propertyName: 'Tirumala Grand Residency',
      roomNumber: '302',
      watchlistMatch: true,
      watchlistReason: 'Interpol Watchlist (Financial Crime)',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
      status: 'Watchlist Match'
    },
    {
      id: 'CHK-1023',
      guestName: 'K. Rajesh Kumar',
      age: 29,
      phone: '+91 93910 88273',
      idType: 'PAN Card',
      idNumber: 'APNPK1128L',
      idImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&q=80',
      nationality: 'Indian',
      checkinTime: '2026-06-05T19:12:00Z',
      propertyName: 'V-Residency Luxury Coliving',
      roomNumber: '408',
      watchlistMatch: false,
      watchlistReason: '',
      photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&q=80',
      status: 'Cleared'
    },
    {
      id: 'CHK-1024',
      guestName: 'Shaik Ameer',
      age: 23,
      phone: '+91 99882 11029',
      idType: 'Driving License',
      idNumber: 'AP0162021008272',
      idImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80',
      nationality: 'Indian',
      checkinTime: '2026-06-05T19:14:00Z',
      propertyName: 'Executive PG for Men',
      roomNumber: '201',
      watchlistMatch: true,
      watchlistReason: 'Local Police Alert: Cyber Fraud Allegation',
      photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80',
      status: 'Escalated'
    }
  ],
  alerts: [
    { id: 'ALT-101', type: 'sos', message: 'Active SOS Alert triggered from Venkata Sai Elite Women\'s PG (Vijayawada)', time: '2 mins ago', severity: 'critical', propertyId: 'PROP-001' },
    { id: 'ALT-102', type: 'watchlist', message: 'Watchlist match detected: Michael Corleone (US National) at Tirumala Grand Residency', time: '14 mins ago', severity: 'warning', propertyId: 'PROP-003' },
    { id: 'ALT-103', type: 'compliance', message: 'Critical compliance drop: Sri Krishna Luxury Stay score dropped below 50%', time: '1 hour ago', severity: 'warning', propertyId: 'PROP-004' },
    { id: 'ALT-104', type: 'foreign', message: 'Foreign national check-in: Michael Corleone (US) at Tirumala Grand Residency', time: '14 mins ago', severity: 'info', propertyId: 'PROP-003' },
  ],
  incidents: [
    {
      id: 'INC-2026-08',
      propertyName: 'Venkata Sai Elite Women\'s PG',
      district: 'NTR Vijayawada',
      type: 'SOS Button Triggered',
      reportedAt: '2026-06-05T19:24:00Z',
      assignedOfficer: 'Inspector Ramesh Babu (Vijayawada North)',
      status: 'Dispatch Active', // Dispatch Active, Under Investigation, Resolved
      details: 'Panic button pressed in Room 104. Automated call dispatched. Officer patrol vehicle AP-16-P-0220 responding.'
    },
    {
      id: 'INC-2026-07',
      propertyName: 'V-Residency Luxury Coliving',
      district: 'Visakhapatnam City',
      type: 'Unregistered Co-Guest',
      reportedAt: '2026-06-04T11:20:00Z',
      assignedOfficer: 'SI Prasad (Madhurawada PS)',
      status: 'Under Investigation',
      details: 'Audit check revealed discrepancy of 3 occupants in Room 102 who did not upload Aadhar credentials.'
    }
  ]
};
